/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XmichaliklAmbulanceWlList {
    }
}
declare global {
    interface HTMLXmichaliklAmbulanceWlListElement extends Components.XmichaliklAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXmichaliklAmbulanceWlListElement: {
        prototype: HTMLXmichaliklAmbulanceWlListElement;
        new (): HTMLXmichaliklAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xmichalikl-ambulance-wl-list": HTMLXmichaliklAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XmichaliklAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xmichalikl-ambulance-wl-list": XmichaliklAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xmichalikl-ambulance-wl-list": LocalJSX.XmichaliklAmbulanceWlList & JSXBase.HTMLAttributes<HTMLXmichaliklAmbulanceWlListElement>;
        }
    }
}
